Refactor device/track manager
fishjam-cloud/web-client-sdk pull request #36
Opened 2024-07-11 14:02 UTC by czerwiukk

## Description

Deduplication of device manager code, general improvements.
Groundwork for further improvements, especially `Client.ts` removal.

Feel invited to point out possible further improvements, it'd be best to write them down as separate tasks.

## Motivation and Context

This change strives to improve the codebase quality and maintainability.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

2024-07-16 07:40 UTC, czerwiukk commented on packages/react-client/src/Client.ts
>      },
definitely beneficial, though I'd strive to remove this whole file in the future

2024-07-16 11:45 UTC, kamil-stasiak requested changes

2024-07-16 11:45 UTC, kamil-stasiak commented on packages/react-client/src/Client.ts
> +      this.emit("managerInitialized", { mediaDeviceType: "userMedia" }, this);
Only the `userMedia` manager has an `init` method and can be initialized, so I think this` { mediaDeviceType: "userMedia" }` isn't very useful

2024-07-16 11:45 UTC, kamil-stasiak commented on packages/react-client/src/DeviceManager.ts
> +    this.emit("managerInitialized", this.deviceState);
Now this event is emitted twice (once for every device manager). Maybe it should be moved to `initializeDevices`

2024-07-17 07:20 UTC, czerwiukk commented on packages/react-client/src/mediaInitializer.ts
> +) => {
resolved

2024-07-17 13:28 UTC, kamil-stasiak approved these changes

2024-07-17 13:40 UTC, merged